(()=>{
  const root=document.querySelector('#msa');
  const panel=root?.querySelector('.view[data-panel="inventory"]');
  if(!root||!panel||panel.dataset.inventoryViewEngine)return;
  panel.dataset.inventoryViewEngine='1';

  const state={preset:'main-stock',offset:0,limit:100,q:'',mappingStatus:'',sourceClassification:'',reviewReason:'',presets:[],registry:[],columns:null,loading:false,items:[],columnsRendered:[],selected:new Set(),drawerIndex:null};
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const api=async(path,opts={})=>{const headers={'Accept':'application/json',...(opts.body?{'Content-Type':'application/json'}:{}),...(opts.headers||{})};const res=await fetch(path,{credentials:'same-origin',...opts,headers});let data=null;try{data=await res.json()}catch{}if(!res.ok)throw new Error(data?.detail||`Request failed: ${res.status}`);return data};
  const rowKey=(item,index)=>String(item.product_id||item.lot_id||item.source_row_no||`${state.preset}:${state.offset+index}`);
  const isReviewPreset=()=>state.preset==='migration-review'||state.preset==='cms-mapping-review';

  panel.innerHTML=`
    <div class="inventory-view-head">
      <div><div class="inventory-view-kicker">Configurable Inventory View</div><h2 id="inventoryViewName">Main Stock</h2><p id="inventoryViewDescription" class="sub">Loading view definition…</p></div>
      <div class="inventory-shadow-banner"><strong>Shadow inventory — not canonical</strong><span>Google Sheet remains operational authority · baseline review in progress</span></div>
    </div>
    <div class="inventory-view-toolbar">
      <label>View<select id="inventoryPresetSelect"><option value="main-stock">Main Stock</option></select></label>
      <label class="inventory-search-label">Search<input id="inventoryViewSearch" type="search" placeholder="Search item or CMS evidence…"></label>
      <button class="secondary" id="inventoryColumnsToggle" type="button">Columns</button>
      <button class="secondary" id="inventoryViewRefresh" type="button">Refresh</button>
    </div>
    <div class="inventory-review-filters" id="inventoryReviewFilters" hidden>
      <label>Mapping status<select id="inventoryMappingStatus"><option value="">All mapping states</option><option>REVIEW_REQUIRED</option><option>CMS_DISCONTINUED</option><option>RECYCLED_CODE</option><option>UNMAPPED</option><option>ACTIVE_MATCH</option></select></label>
      <label id="inventoryClassificationLabel">Source class<select id="inventorySourceClassification"><option value="">All source classes</option><option>SAFE</option><option>REVIEW</option><option>CONFLICT</option><option>NEW_UNMAPPED</option></select></label>
      <label class="inventory-reason-filter">Review reason<input id="inventoryReviewReason" type="search" placeholder="Contains…"></label>
      <button class="secondary" id="inventoryClearFilters" type="button">Clear filters</button>
    </div>
    <div class="inventory-column-panel" id="inventoryColumnPanel" hidden>
      <div class="inventory-column-panel-head"><div><strong>Visible columns</strong><span>Registry fields only — this does not change database structure.</span></div><button class="secondary" id="inventoryColumnsReset" type="button">Reset preset</button></div>
      <div class="inventory-column-grid" id="inventoryColumnGrid"></div><div class="inventory-column-actions"><button id="inventoryColumnsApply" type="button">Apply columns</button></div>
    </div>
    <div class="inventory-selection-bar" id="inventorySelectionBar" hidden>
      <div class="inventory-selection-copy"><strong id="inventorySelectionCount">0 selected</strong><span>Review context only — no acceptance or mutation.</span></div>
      <div class="inventory-selection-actions"><button class="secondary" id="inventoryAskAI" type="button">Ask AI</button><button class="secondary" id="inventoryDeepReview" type="button">Deep Review</button><button class="secondary" id="inventoryClearSelection" type="button">Clear</button></div>
    </div>
    <div class="inventory-view-meta" id="inventoryViewMeta">Loading…</div>
    <div class="inventory-view-table-wrap">
      <table class="inventory-view-table" id="inventoryViewTable"><thead></thead><tbody></tbody></table>
      <div class="inventory-view-empty" id="inventoryViewEmpty">Loading inventory view…</div>
    </div>
    <div class="inventory-view-pager"><button class="secondary" id="inventoryPrev" type="button">← Previous</button><span id="inventoryPageLabel">Rows 1–100</span><button class="secondary" id="inventoryNext" type="button">Next →</button></div>
    <aside class="inventory-review-drawer" id="inventoryReviewDrawer" aria-label="Review detail" hidden>
      <div class="inventory-drawer-head"><div><span>Review detail</span><strong id="inventoryDrawerTitle">Selected row</strong></div><button class="secondary" id="inventoryDrawerClose" type="button" aria-label="Close review detail">Close</button></div>
      <div id="inventoryDrawerBody"></div>
    </aside>`;

  const $=s=>panel.querySelector(s),table=$('#inventoryViewTable'),thead=table.querySelector('thead'),tbody=table.querySelector('tbody'),empty=$('#inventoryViewEmpty'),meta=$('#inventoryViewMeta'),presetSelect=$('#inventoryPresetSelect'),search=$('#inventoryViewSearch'),columnsPanel=$('#inventoryColumnPanel'),columnGrid=$('#inventoryColumnGrid'),filters=$('#inventoryReviewFilters'),mappingStatus=$('#inventoryMappingStatus'),sourceClassification=$('#inventorySourceClassification'),reviewReason=$('#inventoryReviewReason'),selectionBar=$('#inventorySelectionBar'),drawer=$('#inventoryReviewDrawer'),askAI=$('#inventoryAskAI'),deepReview=$('#inventoryDeepReview');

  function readableToken(value){return String(value??'').trim().replace(/[_-]+/g,' ').replace(/\s+/g,' ').toLowerCase().replace(/(^|[\s/])\p{L}/gu,m=>m.toUpperCase())}
  function categoryLabel(value){const key=String(value??'').trim().toUpperCase();const known={CONTINUITY_EXACT_NAME_PRICE_SAME:'Continuity: exact name, same price',CONTINUITY_EXACT_NAME_PRICE_CHANGED:'Continuity: exact name, price changed',MULTIPLE_SOURCE_CODES:'Multiple CMS codes in source',CMS_DISCONTINUED:'CMS item discontinued; local item retained',CODE_NAME_MISMATCH:'CMS code/name mismatch',UNMAPPED:'No CMS mapping found',NEW_UNMAPPED:'New item without CMS mapping',MISSING_SOURCE_CMS_NAME:'Source CMS name is missing',MULTIPLE_SOURCE_CMS_NAMES:'Multiple source CMS names',RECYCLED_CODE:'CMS code appears recycled'};return known[key]||readableToken(key)||'Review evidence'}
  function reasonEvidence(value){if(value===null||value===undefined||value==='')return {summary:'—',details:[]};if(typeof value!=='string')return {summary:String(value),details:[]};const raw=value.trim();if(!(raw.startsWith('{')&&raw.endsWith('}')))return {summary:raw,details:[]};try{const parsed=JSON.parse(raw);if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')return {summary:raw,details:[]};const category=parsed.category??parsed.reason_code??parsed.code;const preferred=parsed.message??parsed.reason??parsed.summary??parsed.detail;const summary=preferred?String(preferred):categoryLabel(category);const details=[];if(category)details.push(['Category',categoryLabel(category)]);Object.entries(parsed).forEach(([key,val])=>{if(['category','reason_code','code','message','reason','summary','detail'].includes(key)||val===null||val===undefined||val==='')return;const text=typeof val==='object'?(Array.isArray(val)?val.join(', '):Object.entries(val).map(([k,v])=>`${readableToken(k)}: ${v}`).join(' · ')):String(val);details.push([readableToken(key),text])});return {summary,details}}catch{return {summary:raw,details:[]}}}
  function format(value,def,field){if(field==='review_reason')return reasonEvidence(value).summary;if(value===null||value===undefined||value==='')return '—';if(def?.data_type==='decimal'){const n=Number(value);return Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:3}):String(value)}if(def?.data_type==='date'){const d=new Date(`${value}T00:00:00`);return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString()}return String(value)}
  function cellClass(field,value){if(field==='mapping_status'||field==='source_classification')return ` inventory-status-cell status-${String(value||'none').toLowerCase().replace(/[^a-z0-9]+/g,'-')}`;if(field.endsWith('_qty')||field.includes('price'))return ' inventory-number-cell';return ''}
  function rowClass(item){const values=[item.source_classification,item.mapping_status].filter(Boolean).map(String);if(values.includes('CONFLICT')||values.includes('RECYCLED_CODE'))return 'inventory-row-critical';if(values.includes('REVIEW')||values.includes('REVIEW_REQUIRED')||values.includes('CMS_DISCONTINUED')||values.includes('NEW_UNMAPPED')||values.includes('UNMAPPED'))return 'inventory-row-review';return ''}
  function renderColumns(columns){thead.innerHTML=`<tr><th class="inventory-select-col" aria-label="Select rows"></th>${columns.map(col=>`<th style="${col.width?`min-width:${Number(col.width)}px`:''}">${esc(col.label)}</th>`).join('')}</tr>`}
  function selectedIndices(){const result=[];state.items.forEach((item,index)=>{if(state.selected.has(rowKey(item,index)))result.push(index)});return result}
  function updateSelection(){const tooMany=state.selected.size>20;selectionBar.hidden=state.selected.size===0;$('#inventorySelectionCount').textContent=`${state.selected.size.toLocaleString()} selected`;askAI.hidden=!isReviewPreset();deepReview.hidden=!isReviewPreset();askAI.disabled=tooMany;deepReview.disabled=tooMany;askAI.title=tooMany?'Select at most 20 rows for AI review.':'Build a read-only server-rehydrated review context.';deepReview.title=tooMany?'Select at most 20 rows for Deep Review.':'Prefill the existing Owner Multi-Agent REVIEW workspace without running it.';tbody.querySelectorAll('tr[data-row-key]').forEach(tr=>tr.classList.toggle('inventory-row-selected',state.selected.has(tr.dataset.rowKey)))}
  function renderRows(columns,items){tbody.innerHTML='';state.items=items;state.columnsRendered=columns;if(!items.length){empty.textContent='No rows match this view and filters.';empty.hidden=false;table.hidden=true;return}empty.hidden=true;table.hidden=false;const fragment=document.createDocumentFragment();items.forEach((item,index)=>{const key=rowKey(item,index),tr=document.createElement('tr');tr.dataset.rowKey=key;tr.dataset.rowIndex=String(index);tr.className=rowClass(item);tr.innerHTML=`<td class="inventory-select-col"><input type="checkbox" class="inventory-row-check" aria-label="Select row" ${state.selected.has(key)?'checked':''}></td>`+columns.map(col=>{const value=item[col.field],text=format(value,col.field_definition,col.field);return `<td class="${cellClass(col.field,value)}" title="${esc(text)}">${esc(text)}</td>`}).join('');fragment.appendChild(tr)});tbody.appendChild(fragment);updateSelection()}
  function renderColumnPicker(view){const defaults=new Set(view.columns.map(c=>c.field)),selected=new Set(state.columns||[...defaults]),presetOrder=view.columns.map(c=>c.field),extras=state.registry.map(f=>f.key).filter(k=>!presetOrder.includes(k)),ordered=[...presetOrder,...extras],defs=new Map(state.registry.map(f=>[f.key,f]));columnGrid.innerHTML=ordered.map(key=>{const def=defs.get(key);if(!def)return '';return `<label class="inventory-column-option"><input type="checkbox" value="${esc(key)}" ${selected.has(key)?'checked':''}><span><strong>${esc(def.label)}</strong><small>${esc(def.kind)}</small></span></label>`}).join('')}
  function syncReviewControls(){const review=isReviewPreset();filters.hidden=!review;$('#inventoryClassificationLabel').hidden=state.preset!=='migration-review';if(!review){state.mappingStatus='';state.sourceClassification='';state.reviewReason='';mappingStatus.value='';sourceClassification.value='';reviewReason.value=''}}
  function drawerPair(label,leftLabel,leftValue,rightLabel,rightValue){const mismatch=String(leftValue??'')!==String(rightValue??'');return `<div class="inventory-compare-row ${mismatch?'is-mismatch':''}"><strong>${esc(label)}</strong><div><span>${esc(leftLabel)}</span><b>${esc(leftValue??'—')}</b></div><div><span>${esc(rightLabel)}</span><b>${esc(rightValue??'—')}</b></div></div>`}
  function reasonDrawer(value){const evidence=reasonEvidence(value);const details=evidence.details.length?`<div class="inventory-detail-grid">${evidence.details.map(([label,text])=>`<div><span>${esc(label)}</span><strong>${esc(text)}</strong></div>`).join('')}</div>`:'';return `<p>${esc(evidence.summary==='—'?'No review reason recorded.':evidence.summary)}</p>${details}`}
  function openDrawer(index){const item=state.items[index];if(!item)return;state.drawerIndex=index;$('#inventoryDrawerTitle').textContent=item.local_item_name||item.cms_name||`Row ${state.offset+index+1}`;let html='';if(state.preset==='migration-review'){html+=`<div class="inventory-compare-grid">${drawerPair('Quantity','Source',item.source_current_qty,'Shadow',item.current_qty)}${drawerPair('CMS code','Source / resolved',item.cms_code,'Mapping',item.cms_code)}${drawerPair('Expiry','Source',item.expiry_date,'Shadow',item.expiry_date)}</div>`}else if(state.preset==='cms-mapping-review'){html+=`<div class="inventory-detail-grid"><div><span>CMS code</span><strong>${esc(item.cms_code??'—')}</strong></div><div><span>CMS name</span><strong>${esc(item.cms_name??'—')}</strong></div><div><span>Current catalogue price</span><strong>${esc(item.catalogue_price??'—')}</strong></div><div><span>Accepted store price</span><strong>${esc(item.accepted_operational_price??'—')}</strong></div></div>`}else{html+=`<div class="inventory-detail-grid"><div><span>Current quantity</span><strong>${esc(item.current_qty??'—')}</strong></div><div><span>CMS code</span><strong>${esc(item.cms_code??'—')}</strong></div></div>`}html+=`<div class="inventory-review-summary"><div><span>Mapping status</span><strong>${esc(item.mapping_status??'—')}</strong></div>${item.source_classification!==undefined?`<div><span>Source class</span><strong>${esc(item.source_classification??'—')}</strong></div>`:''}<div class="span-2"><span>Review reason</span>${reasonDrawer(item.review_reason)}</div></div><p class="inventory-readonly-note">Read-only evidence view. Selecting or opening this row does not accept a mapping, price, or inventory change.</p>`;$('#inventoryDrawerBody').innerHTML=html;drawer.hidden=false}
  function evidenceLines(context){const lines=[];context.rows.forEach((row,index)=>{lines.push(`${index+1}. ${row.local_item_name||row.cms_name||`Row ${index+1}`}`);context.view.columns.forEach(column=>{let value=row[column.field];if(value===null||value===undefined||value==='')return;if(column.field==='review_reason')value=reasonEvidence(value).summary;lines.push(`- ${column.label}: ${value}`)});lines.push('')});return lines}
  function buildAiDraft(context){return [`Review these ${context.selected_count} selected rows from ${context.view.name}.`,'This is server-rehydrated shadow review evidence and is not canonical. Explain, compare, summarize and prioritize only; do not claim or perform mapping, price, inventory, baseline or canonical changes.','','Selected evidence:',...evidenceLines(context)].join('\n').trim()}
  function buildDeepReviewTask(context){return [`Perform a deep multi-agent review of these ${context.selected_count} selected rows from ${context.view.name}.`,'Use only the supplied server-rehydrated shadow review evidence. Analyze discrepancies and review reasons, challenge uncertain conclusions, and synthesize Owner-facing recommendations. Do not treat PostgreSQL/shadow data as canonical and do not claim or perform mapping acceptance, price changes, inventory changes, migration-baseline acceptance, or canonical promotion.','','Selected evidence:',...evidenceLines(context)].join('\n').trim()}
  function handoffCard(context,mode){const existing=root.querySelector(`.inventory-ai-handoff-card[data-mode="${mode}"]`);if(existing)existing.remove();const card=document.createElement('section');card.className='inventory-ai-handoff-card';card.dataset.mode=mode;const names=context.rows.slice(0,4).map(row=>row.local_item_name||row.cms_name||'Selected row');card.innerHTML=`<div class="inventory-ai-handoff-head"><div><strong>${mode==='chat'?'Start a new Inventory chat':'Deep Review context ready'}</strong><span>${context.selected_count} selected · ${esc(context.view.name)}</span></div><b>${mode==='chat'?'Choose agent':'Review not started'}</b></div><div class="inventory-ai-handoff-items">${names.map(name=>`<span>${esc(name)}</span>`).join('')}${context.selected_count>names.length?`<span>+${context.selected_count-names.length} more</span>`:''}</div><p>${mode==='chat'?'Choose the agent for this context. A fresh conversation will be created before the prompt is attached.':'Work title and task are prefilled. You can choose the REVIEW preset and start the existing native workflow here without scrolling.'}</p>`;return card}
  async function requestSelectedContext(){if(!isReviewPreset()||!state.selected.size)throw new Error('Select review rows first.');if(state.selected.size>20)throw new Error('Select at most 20 rows for one AI review context.');const indices=selectedIndices();if(!indices.length)throw new Error('Select review rows first.');return api('/dashboard/api/inventory-view/review-context',{method:'POST',body:JSON.stringify({preset:state.preset,offset:state.offset,limit:state.limit,q:state.q||null,mapping_status:state.mappingStatus||null,source_classification:state.preset==='migration-review'?(state.sourceClassification||null):null,review_reason:state.reviewReason||null,selected_indices:indices})})}
  async function waitForNewConversation(previousId,timeoutMs=7000){const started=Date.now();while(Date.now()-started<timeoutMs){const active=root.querySelector('.ai-conversation-item.active')?.dataset.aiConversationRow||null,form=root.querySelector('#aiChatForm');if(active&&active!==previousId&&form&&!form.hidden)return active;await new Promise(resolve=>setTimeout(resolve,60))}throw new Error('New AI conversation did not become ready.')}
  async function waitForReviewComposer(timeoutMs=7000){const started=Date.now();while(Date.now()-started<timeoutMs){const title=root.querySelector('#reviewTitle'),task=root.querySelector('#reviewTask'),run=root.querySelector('#reviewRun'),preset=root.querySelector('#reviewSessionSelect');const loading=preset?.options?.length===1&&/Loading/i.test(preset.options[0]?.textContent||'');if(title&&task&&run&&preset&&!loading)return {title,task,run,preset};await new Promise(resolve=>setTimeout(resolve,60))}throw new Error('Multi-Agent Review workspace did not become ready.')}
  function addChatStarter(context,card){const canonicalAgent=root.querySelector('#aiAgentSelect'),newChat=root.querySelector('#aiNewConversation'),input=root.querySelector('#aiMessageInput'),form=root.querySelector('#aiChatForm'),thread=root.querySelector('#aiChatThread');if(!canonicalAgent||!newChat||!input||!form||!thread)throw new Error('AI Workspace new-chat controls are not available.');const controls=document.createElement('div');controls.style.cssText='display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:end;margin-top:10px';controls.innerHTML=`<label style="display:flex;flex-direction:column;gap:5px;font-size:.72rem;font-weight:700">Agent<select data-inventory-chat-agent style="min-height:42px;width:100%">${canonicalAgent.innerHTML}</select></label><button type="button" data-inventory-start-chat>Start new chat</button>`;card.appendChild(controls);const quick=controls.querySelector('[data-inventory-chat-agent]'),start=controls.querySelector('[data-inventory-start-chat]');if(canonicalAgent.value)quick.value=canonicalAgent.value;input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));form.hidden=true;thread.hidden=true;start.addEventListener('click',async()=>{if(!quick.value){window.alert('Choose an agent first.');return}start.disabled=true;start.textContent='Creating…';const previous=root.querySelector('.ai-conversation-item.active')?.dataset.aiConversationRow||null;canonicalAgent.value=quick.value;canonicalAgent.dispatchEvent(new Event('change',{bubbles:true}));newChat.click();try{await waitForNewConversation(previous);thread.hidden=false;form.hidden=false;input.value=buildAiDraft(context);input.dispatchEvent(new Event('input',{bubbles:true}));quick.disabled=true;start.textContent='New chat ready';card.querySelector('.inventory-ai-handoff-head b').textContent='Not sent yet';card.querySelector('p').textContent='Fresh chat created with the selected agent. Review the prefilled prompt, then press Send when ready.';root.dispatchEvent(new CustomEvent('msa:inventory-review-context-ready',{detail:{context,new_chat:true}}));setTimeout(()=>{card.scrollIntoView({block:'nearest'});input.focus()},0)}catch(err){thread.hidden=false;form.hidden=false;start.disabled=false;start.textContent='Start new chat';window.alert(err.message)}})}
  function addDeepQuickControls(card,composer){const config=root.querySelector('.review-config');const controls=document.createElement('div');controls.style.cssText='display:grid;grid-template-columns:minmax(0,1fr);gap:8px;margin-top:10px';controls.innerHTML=`<label style="display:flex;flex-direction:column;gap:5px;font-size:.72rem;font-weight:700">REVIEW preset<select data-inventory-review-preset style="min-height:42px;width:100%">${composer.preset.innerHTML}</select></label><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px"><button class="secondary" type="button" data-inventory-review-roles>Review roles</button><button type="button" data-inventory-run-review>Run native review</button></div>`;card.appendChild(controls);const quick=controls.querySelector('[data-inventory-review-preset]');quick.value=composer.preset.value;quick.addEventListener('change',()=>{composer.preset.value=quick.value;composer.preset.dispatchEvent(new Event('change',{bubbles:true}));card.querySelector('.inventory-ai-handoff-head b').textContent=quick.value?'Preset selected':'Review not started'});controls.querySelector('[data-inventory-review-roles]').addEventListener('click',()=>config?.scrollIntoView({behavior:'smooth',block:'start'}));controls.querySelector('[data-inventory-run-review]').addEventListener('click',()=>{if(!quick.value){window.alert('Choose a REVIEW preset first.');return}if(composer.preset.value!==quick.value){composer.preset.value=quick.value;composer.preset.dispatchEvent(new Event('change',{bubbles:true}))}composer.run.click()})}
  async function askSelectedRows(){if(!isReviewPreset()||!state.selected.size)return;askAI.disabled=true;const original=askAI.textContent;askAI.textContent='Preparing…';try{const context=await requestSelectedContext();const nav=root.querySelector('#aiWorkspaceNav'),chatTab=root.querySelector('.ai-workspace-tab[data-ai-tab="chat"]'),input=root.querySelector('#aiMessageInput');if(!nav||!chatTab||!input)throw new Error('AI Workspace Chat is not available in this dashboard');nav.click();chatTab.click();const form=input.closest('#aiChatForm')||input.closest('form'),card=handoffCard(context,'chat');if(form?.parentNode)form.parentNode.insertBefore(card,form);addChatStarter(context,card);setTimeout(()=>card.scrollIntoView({block:'nearest'}),0)}catch(err){window.alert(err.message)}finally{askAI.textContent=original;askAI.disabled=state.selected.size>20}}
  async function deepReviewSelectedRows(){if(!isReviewPreset()||!state.selected.size)return;deepReview.disabled=true;const original=deepReview.textContent;deepReview.textContent='Preparing…';try{const context=await requestSelectedContext();const nav=root.querySelector('#aiWorkspaceNav'),multiTab=root.querySelector('#aiMultiTab');if(!nav||!multiTab||multiTab.hidden)throw new Error('Owner Multi-Agent Review is not available for this account.');nav.click();multiTab.click();const composer=await waitForReviewComposer();composer.title.value=`Deep review · ${context.view.name} · ${context.selected_count} row${context.selected_count===1?'':'s'}`;composer.task.value=buildDeepReviewTask(context);composer.title.dispatchEvent(new Event('input',{bubbles:true}));composer.task.dispatchEvent(new Event('input',{bubbles:true}));const compose=composer.title.closest('.review-compose')||composer.title.parentElement,card=handoffCard(context,'deep');const head=compose?.querySelector('.review-section-head');if(head)head.insertAdjacentElement('afterend',card);else compose?.prepend(card);addDeepQuickControls(card,composer);root.dispatchEvent(new CustomEvent('msa:inventory-deep-review-context-ready',{detail:{context}}));setTimeout(()=>{card.scrollIntoView({block:'nearest'});composer.task.focus()},0)}catch(err){window.alert(err.message)}finally{deepReview.textContent=original;deepReview.disabled=state.selected.size>20}}
  async function loadDefinitions(){const [presets,registry]=await Promise.all([api('/dashboard/api/inventory-view/presets'),api('/dashboard/api/inventory-view/registry')]);state.presets=presets.items||[];state.registry=registry.fields||[];presetSelect.innerHTML=state.presets.map(view=>`<option value="${esc(view.view_id)}">${esc(view.name)}</option>`).join('');presetSelect.value=state.preset}
  async function load(){if(state.loading)return;state.loading=true;empty.hidden=false;empty.textContent='Loading inventory view…';table.hidden=true;meta.textContent='Loading…';try{if(!state.presets.length)await loadDefinitions();syncReviewControls();const params=new URLSearchParams({preset:state.preset,limit:String(state.limit),offset:String(state.offset)});if(state.q)params.set('q',state.q);if(state.columns?.length)params.set('fields',state.columns.join(','));if(state.mappingStatus)params.set('mapping_status',state.mappingStatus);if(state.sourceClassification&&state.preset==='migration-review')params.set('source_classification',state.sourceClassification);if(state.reviewReason)params.set('review_reason',state.reviewReason);const data=await api('/dashboard/api/inventory-view/rows?'+params.toString()),view=data.view,columns=data.columns||[],items=data.items||[];$('#inventoryViewName').textContent=view.name;$('#inventoryViewDescription').textContent=view.description;renderColumns(columns);renderRows(columns,items);renderColumnPicker(view);meta.textContent=`${view.row_grain.replaceAll('_',' ')} · Store ${view.store_scope} · ${items.length.toLocaleString()} rows shown · Read-only shadow projection`;const start=items.length?state.offset+1:0,end=state.offset+items.length;$('#inventoryPageLabel').textContent=`Rows ${start.toLocaleString()}–${end.toLocaleString()}`;$('#inventoryPrev').disabled=state.offset===0;$('#inventoryNext').disabled=items.length<state.limit}catch(err){empty.hidden=false;table.hidden=true;empty.textContent=err.message;meta.textContent='Unable to load configurable inventory view.'}finally{state.loading=false}}

  let timer=null,reasonTimer=null;
  presetSelect.addEventListener('change',()=>{state.preset=presetSelect.value;state.offset=0;state.columns=null;state.selected.clear();drawer.hidden=true;syncReviewControls();load()});
  search.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{state.q=search.value.trim();state.offset=0;load()},180)});
  mappingStatus.addEventListener('change',()=>{state.mappingStatus=mappingStatus.value;state.offset=0;load()});
  sourceClassification.addEventListener('change',()=>{state.sourceClassification=sourceClassification.value;state.offset=0;load()});
  reviewReason.addEventListener('input',()=>{clearTimeout(reasonTimer);reasonTimer=setTimeout(()=>{state.reviewReason=reviewReason.value.trim();state.offset=0;load()},180)});
  $('#inventoryClearFilters').addEventListener('click',()=>{state.mappingStatus='';state.sourceClassification='';state.reviewReason='';mappingStatus.value='';sourceClassification.value='';reviewReason.value='';state.offset=0;load()});
  $('#inventoryViewRefresh').addEventListener('click',()=>load());
  $('#inventoryColumnsToggle').addEventListener('click',()=>{columnsPanel.hidden=!columnsPanel.hidden});
  $('#inventoryColumnsReset').addEventListener('click',()=>{state.columns=null;columnsPanel.hidden=true;load()});
  $('#inventoryColumnsApply').addEventListener('click',()=>{const selected=[...columnGrid.querySelectorAll('input:checked')].map(input=>input.value);if(!selected.length)return;state.columns=selected;state.offset=0;columnsPanel.hidden=true;load()});
  $('#inventoryPrev').addEventListener('click',()=>{state.offset=Math.max(0,state.offset-state.limit);drawer.hidden=true;load()});
  $('#inventoryNext').addEventListener('click',()=>{state.offset+=state.limit;drawer.hidden=true;load()});
  $('#inventoryClearSelection').addEventListener('click',()=>{state.selected.clear();tbody.querySelectorAll('.inventory-row-check').forEach(input=>{input.checked=false});updateSelection()});
  askAI.addEventListener('click',askSelectedRows);
  deepReview.addEventListener('click',deepReviewSelectedRows);
  $('#inventoryDrawerClose').addEventListener('click',()=>{drawer.hidden=true;state.drawerIndex=null});
  tbody.addEventListener('click',event=>{const tr=event.target.closest('tr[data-row-index]');if(!tr)return;const index=Number(tr.dataset.rowIndex),key=tr.dataset.rowKey;if(event.target.matches('.inventory-row-check')){event.stopPropagation();event.target.checked?state.selected.add(key):state.selected.delete(key);updateSelection();return}openDrawer(index)});
  root.addEventListener('click',event=>{const nav=event.target.closest('.nav-btn[data-view="inventory"]');if(nav)setTimeout(load,0)});
  load();
})();