from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"missing docs anchor in {path}: {old[:100]!r}")
    file.write_text(text.replace(old, new, 1), encoding="utf-8")


replace_once(
    "IMPLEMENTATION_PLAN.md",
    "### 5.6A Inventory Sheet Interaction Foundation v1 — ACTIVE",
    "### 5.6A Inventory Sheet Interaction Foundation v1 — COMPLETE + PRODUCTION VERIFIED",
)
replace_once(
    "IMPLEMENTATION_PLAN.md",
    """Next bounded work:\n\n- [ ] Add one-click Clear all for Search + review filters + sort state if retained as a useful workbench action; per-chip clearing is already complete.\n- [ ] Add keyboard navigation/copy shortcuts after the export/sort/layout substrate is stable.\n- [ ] Add optional desktop split-pane review detail after core table ergonomics are proven.\n\n### 5.7 Slice E — saved custom views\n\n- [ ] Persist user-defined view definitions.\n- [ ] View Builder: row grain, Store scope, field selection/order, labels, widths, filters/sorts/groups/formatting.\n- [ ] Persist user-owned layout preferences such as column order/width/density/sort where appropriate.\n- [ ] Duplicate a system preset into a user-owned view without mutating the system preset.\n- [ ] Route user-created tabular views through the same reusable Excel export renderer instead of implementing a second export stack.\n- [ ] Never permit arbitrary SQL/raw DB expressions.\n""",
    """Next bounded work:\n\n- [x] One-click Clear all for Search + review filters + sort state.\n- [x] Cell-first keyboard navigation, Shift-range extension, and selection-aware TSV copy.\n- [ ] Optional desktop split-pane review detail remains deferred; it is not required for Slice E.\n\n### 5.7 Slice E — saved custom views / Custom Table Builder — ACTIVE\n\n#### E1 Saved View Persistence Foundation — COMPLETE + PRODUCTION VERIFIED\n\n- [x] Persist authenticated user-owned saved view definitions in `inventory_saved_views`.\n- [x] Persist registered field order, widths, density, bounded filters/sort, and presentation-only fills.\n- [x] Save view / Save as / Delete view with refresh/reopen rehydration and owner scoping.\n- [x] Preserve immutable system presets and non-canonical/read-only authority boundaries.\n- [x] PR #207 merged and production deployment verified at main SHA `82abd4f83a5e6a88af8714983a91b151fc5c642e`.\n\n#### E2 Custom Table Builder v1 — IMPLEMENTED + EXACT-HEAD CI GREEN, PR #209 OPEN\n\n- [x] First-class `New table` builder over allowlisted server-owned row sources.\n- [x] Select/remove/reorder registered mapped fields independently of preset visible layouts.\n- [x] User-editable header names persisted as `column_labels` while stable field keys remain the mapping identity.\n- [x] Reopen/edit existing custom tables through `Edit table`; Columns panel also supports header-name edits.\n- [x] Reject unknown/unselected, blank, or overlong header labels.\n- [x] Custom-table Excel export resolves the saved custom view's server-owned base preset and preserves current rendered field order + custom headers.\n- [x] Reuse the global Excel/tabular renderer; no parallel export stack.\n- [x] Exact-head CI green at `0cee74672beb369ff745cb451801d8df550224fa`: Inventory View Engine, backend changes, Web production reliability.\n- [ ] Production merge/deploy/runtime proof remains pending until PR #209 is explicitly merged.\n- [ ] Calculated/derived columns remain a later typed-expression slice; arbitrary SQL/raw expressions remain forbidden.\n""",
)

replace_once(
    "ROADMAP.md",
    """Next bounded order:\n\n1. optional one-click Clear all for Search + review filters + sort state if it materially improves the workbench;\n2. keyboard navigation/copy shortcuts after the export/sort/layout substrate is stable;\n3. optional desktop split-pane review detail after table ergonomics are proven;\n4. then Slice E saved custom views / View Builder.\n\nUser-owned persistence of layouts belongs to Slice E rather than being hard-coded into v2.\n\n### Slice E — saved custom views\n\n- persist user-defined view definitions;\n- View Builder for row grain, Store scope, fields/order, labels, widths, filters/sorts/groups/formatting;\n- duplicate a system preset into a user-owned view without mutating the system preset;\n- user-created table/view export reuses the same global Excel renderer rather than adding a second export stack;\n- never permit arbitrary SQL/raw DB expressions.\n""",
    """Next bounded order:\n\n1. Saved View Persistence Foundation is complete and production verified through PR #207.\n2. Custom Table Builder v1 is implemented on PR #209 with exact-head CI green; merge/deploy/runtime proof is the next gate.\n3. Optional desktop split-pane review detail remains deferred and is not a blocker for Slice E.\n4. Calculated/derived columns require a later typed safe-expression design; arbitrary SQL/raw expressions remain forbidden.\n\n### Slice E — saved custom views / Custom Table Builder — ACTIVE\n\n- E1 persists authenticated user-owned saved view definitions, field order, widths, density, filters/sort and presentation-only fills; production verified through PR #207 / main `82abd4f83a5e6a88af8714983a91b151fc5c642e`.\n- E2 adds a first-class `New table` builder over allowlisted server-owned row sources.\n- users select/remove/reorder registered mapped fields and edit header labels independently of stable field keys; labels persist as bounded presentation-only `column_labels`.\n- existing custom tables reopen in `Edit table`; system presets remain immutable.\n- custom-table Excel export resolves the saved base preset and preserves current rendered field order/header labels through the existing global renderer.\n- PR #209 exact-head CI is green at `0cee74672beb369ff745cb451801d8df550224fa`; production merge/deploy proof remains pending.\n- calculated/derived columns remain deferred to a typed safe-expression slice.\n""",
)

replace_once(
    "NEW_CHAT_BOOTSTRAP.md",
    """- Spreadsheet Workbench v2 filter chips, session layout tools, Copy TSV, validated server-side sorting, CSV compatibility export and formatted Excel export are **complete and production-runtime verified**.\n- Inventory now exposes **Export Excel** rather than CSV as the user-facing export action.\n""",
    """- Spreadsheet Workbench v2 filter chips, layout tools, cell/range/row selection, Copy TSV, validated server-side sorting, CSV compatibility export and formatted Excel export are **complete and production-runtime verified**.\n- Saved View Persistence E1 is **complete and production verified** through PR #207 / main `82abd4f83a5e6a88af8714983a91b151fc5c642e`.\n- Custom Table Builder E2 is **implemented on PR #209 with exact-head CI green** at `0cee74672beb369ff745cb451801d8df550224fa`; production merge/deploy proof is still pending.\n- E2 supports `New table`, allowlisted row-source selection, mapped registered fields, field reorder, editable/persisted header names, reopen/edit, and custom-header Excel export parity.\n- Inventory now exposes **Export Excel** rather than CSV as the user-facing export action.\n""",
)
replace_once(
    "NEW_CHAT_BOOTSTRAP.md",
    """Next bounded Inventory work: consider one-click Clear all, then keyboard navigation/copy shortcuts, then optional desktop split-pane review detail. Saved layout persistence and user-created tables belong to Slice E.\n""",
    """Current bounded Inventory work is Slice E. E1 saved-view persistence is production verified. E2 Custom Table Builder v1 is implemented and CI-green on PR #209; the next gate is explicit merge/deploy/runtime proof. Optional desktop split-pane review detail is deferred. Calculated/derived columns remain a later typed-expression design.\n""",
)
replace_once(
    "NEW_CHAT_BOOTSTRAP.md",
    """## Current bounded target — Inventory Sheet Interaction Foundation v1\n\nFormatted Excel export is complete and production-runtime verified. The active Inventory work is now `docs/design/INVENTORY_SHEET_INTERACTION_V1.md`: cell-first selection, rectangular ranges, keyboard navigation, whole-row selector gutter, explicit Details, and selection-aware copy. Do not restore row-wide click-to-open behavior. Whole-row selection remains the only source for Ask AI / Deep Review row context. Fill colors/persistent formatting follow after this v1; Saved Custom Views / View Builder follows the sheet interaction/formatting foundation. All current work remains read-only and PostgreSQL remains non-canonical.\n""",
    """## Current bounded target — Slice E Custom Table Builder v1\n\nSheet Interaction and Sheet Formatting foundations are complete and production verified. E1 Saved View Persistence is production verified through PR #207. E2 Custom Table Builder v1 is implemented on PR #209 with exact-head CI green: blank/new-table workflow, allowlisted row sources, registered field mapping, editable persisted headers, reopen/edit, and custom-header Excel export parity. Do not merge without exact-head green checks; after merge, require auto-deploy and runtime proof. Calculated/derived columns are not part of E2 and require a later typed-expression contract. All current work remains read-only and PostgreSQL remains non-canonical.\n""",
)

print("f6e_e2_docs_sync=pass")
